apiVersion: v1
kind: Service
metadata:
  name: katib-ui
  namespace: kubeflow
  labels:
    app: katib
    component: ui
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31230
      protocol: TCP
      name: ui
  selector:
    app: katib
    component: ui
